# Copyright (c) 2022-2026 Antmicro <www.antmicro.com>
#
# SPDX-License-Identifier: Apache-2.0

[build-system]
requires = ["setuptools>=40.8.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pipeline-manager-prebuilt-frontend"
# Keep in sync with pipeline-manager's version and its "prebuilt" extra URL.
version = "0.0.5"
description = "Prebuilt frontend assets for Pipeline Manager."
authors = [
    {name = "Antmicro Ltd.", email = "contact@antmicro.com"},
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
readme = "README.md"
requires-python = ">=3.9"

[project.urls]
homepage = "https://antmicro.github.io/kenning-pipeline-manager/"
repository = "https://github.com/antmicro/kenning-pipeline-manager"

[tool.setuptools.packages.find]
include = ["pipeline_manager_prebuilt_frontend*"]
namespaces = false

[tool.setuptools.package-data]
pipeline_manager_prebuilt_frontend = ["dist/**/*"]
